#! /bin/sh
### BEGIN INIT INFO
# Provides:             sentinel-production
# Required-Start:       $syslog $remote_fs
# Required-Stop:        $syslog $remote_fs
# Should-Start:         $local_fs
# Should-Stop:          $local_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    sentinel-production - Sentinel instances
# Description:          sentinel-production - Sentinel instances
### END INIT INFO


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/redis-server
NAME=redis-production
DESC=redis-production
RUNDIR=/var/run/sentinel-production

REDISCONF=/etc/redis/sentinel-enabled

test -x $DAEMON || exit 0

if [ -r /etc/default/$NAME ]
then
  . /etc/default/$NAME
fi

#. /lib/lsb/init-functions

set -e

#ToDO
#Run_parts () {
#  if [ -d /etc/redis/${NAME}.${1}.d ]
#  then
#    su redis -s /bin/sh -c "run-parts --exit-on-error /etc/redis/${NAME}.${1}.d"
#  fi
#}

Run_instances() {

  mkdir -p $RUNDIR
  chown -R redis:redis $RUNDIR
  chmod 755 $RUNDIR

  if [ -n "$ULIMIT" ]
  then
    ulimit -n $ULIMIT
  fi

  i=0
  for conf_name in `ls -p $REDISCONF | grep -v /`; do
    #printf "File: %s \n" "$conf_name"
    PIDFILE=${RUNDIR}/${conf_name}.pid
    #printf "PIDFILE: %s \n" "$PIDFILE"
    DAEMON_ARGS=${REDISCONF}/${conf_name}
    #printf "DAEMON_ARGS: %s \n" "$DAEMON_ARGS"

    #Run_parts pre-up

    if start-stop-daemon --start --quiet --oknodo --umask 007 --pidfile $PIDFILE --chuid redis:redis --exec $DAEMON -- $DAEMON_ARGS --sentinel
    then
    #  Run_parts post-up
      echo "$conf_name."
    else
      echo "failed"
    fi
    i=$((i+1))
  done
  printf "Loaded configurations: %d \n" "$i"
}

Stop_instances() {

  for CURPID in `ls -p $RUNDIR | grep -v /`; do
    printf "File: %s \n" "$CURPID"
    PIDFILE=${RUNDIR}/${CURPID}

    if start-stop-daemon --stop --retry forever/TERM/1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
    then
      #Run_parts post-down
      echo "$CURPID."
    else
      echo "failed"
    fi
    rm -f $PIDFILE
    sleep 1
  done
}

case "$1" in
  start)
    echo -n "Starting $DESC: "
    Run_instances
    ;;
  stop)
    echo -n "Stopping $DESC: "
    Stop_instances
    ;;

  restart|force-reload)
    ${0} stop
    ${0} start
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}" >&2
    exit 1
    ;;
esac
exit 0
